[package]
name = "pass_gen"
version = "1.0.0"
authors = ["jeesusmies"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
